name: Build NN6000

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y build-essential clang flex bison gawk gettext git libncurses5-dev libssl-dev rsync unzip zlib1g-dev file wget python3

      - name: Update Feeds
        run: |
          ./scripts/feeds update -a

      - name: Install Feeds
        run: |
          ./scripts/feeds install -a

      - name: Verify Feed Sources
        run: |
          echo "===== EASYTIER ====="
          find feeds -type d | grep easytier || true

          echo "===== NSS ====="
          find package feeds -type d | grep qca-nss || true

      - name: Load Custom Config
        run: |
          cp configs/nn6000.config .config
          make defconfig

      - name: Verify Config After Defconfig
        run: |
          echo "===== FINAL CONFIG ====="

          grep CONFIG_PACKAGE_luci-app-ddns .config || true
          grep CONFIG_PACKAGE_luci-app-acme .config || true
          grep CONFIG_PACKAGE_luci-app-wireguard .config || true
          grep CONFIG_PACKAGE_luci-app-vlmcsd .config || true
          grep CONFIG_PACKAGE_luci-app-easytier .config || true

      - name: Dump Selected Packages
        run: |
          grep "^CONFIG_PACKAGE_.*=y" .config | sort

      - name: Verify NSS Packages
        run: |
          grep qca-nss .config || true
      - name: Verify Passwall2
        run: |
          grep CONFIG_PACKAGE_luci-app-passwall2 .config || true
          grep -R "luci-app-passwall2" feeds/passwall2 || true
          find feeds -type d | grep passwall2 || true
          grep CONFIG_PACKAGE_sing-box .config || true

      - name: Download Sources
        run: |
          make download -j$(nproc)

      - name: Build Firmware
        run: |
          make -j$(nproc)

      - name: Show Manifest
        run: |
          find bin -name "*.manifest" | xargs cat

      - name: Upload Firmware
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: NN6000-Firmware
          path: |
            bin/targets/**/*.bin
            bin/targets/**/*.itb
            bin/targets/**/*.ubi
            bin/targets/**/*.manifest
            bin/targets/**/*.buildinfo
            bin/targets/**/*.json
